package model.auxilio;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ADSI
 */
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class prueba extends javax.swing.JFrame {

    Calendar da = Calendar.getInstance();
    int consulta = 1;
    int s =2;

    /**
     * Creates new form prueba
     */
    public prueba() {
        initComponents();
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel6.setVisible(false);
        jPanel4.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BotonIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        BotonEnviar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BotonConsultar = new javax.swing.JButton();
        jButton1Actualizar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Buscar = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        avisoactuali = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        BotonEliminar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 160, 50, 30);

        BotonIngresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonIngresar.setText("Ingresar");
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonIngresar);
        BotonIngresar.setBounds(370, 380, 100, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 240, 80, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(220, 160, 240, 30);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 320, 190, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Iniciar Sesión");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 50, 150, 30);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(220, 240, 240, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Registrarse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(140, 380, 110, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 500);

        jPanel3.setBackground(new java.awt.Color(150, 177, 207));
        jPanel3.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel3.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("FORMULARIO");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(270, 30, 100, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("nombre");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(110, 100, 70, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("documento");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(110, 160, 90, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("telefono");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(110, 220, 80, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("estrato");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(110, 340, 80, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("barrio");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(110, 280, 80, 20);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(220, 100, 200, 30);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(220, 160, 200, 30);
        jPanel3.add(jTextField9);
        jTextField9.setBounds(220, 220, 200, 30);
        jPanel3.add(jTextField10);
        jTextField10.setBounds(220, 340, 200, 30);
        jPanel3.add(jTextField11);
        jTextField11.setBounds(220, 280, 200, 30);

        BotonEnviar.setBackground(new java.awt.Color(153, 153, 153));
        BotonEnviar.setText("Enviar");
        BotonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnviarActionPerformed(evt);
            }
        });
        jPanel3.add(BotonEnviar);
        BotonEnviar.setBounds(460, 400, 90, 40);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(60, 400, 90, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 600, 500);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        jPanel6.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel6.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setBounds(0,0,600,500);
        jPanel6.setLayout(null);

        jTable2.setBackground(java.awt.SystemColor.controlHighlight);
        jTable2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre", "documento", "telefono", "barrio", "estrato"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 590, 130);

        BotonConsultar.setBackground(java.awt.SystemColor.activeCaption);
        BotonConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonConsultar.setText("Consultar");
        BotonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarActionPerformed(evt);
            }
        });
        jPanel6.add(BotonConsultar);
        BotonConsultar.setBounds(430, 150, 110, 30);

        jButton1Actualizar.setBackground(java.awt.SystemColor.activeCaption);
        jButton1Actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1Actualizar.setText("Actualizar");
        jButton1Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActualizarActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1Actualizar);
        jButton1Actualizar.setBounds(30, 340, 100, 30);

        jButton3.setBackground(java.awt.SystemColor.activeCaption);
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(30, 420, 80, 30);
        jPanel6.add(Buscar);
        Buscar.setBounds(200, 350, 180, 30);

        jButton7.setBackground(java.awt.SystemColor.activeCaption);
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Buscar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7);
        jButton7.setBounds(410, 350, 100, 30);

        avisoactuali.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(avisoactuali);
        avisoactuali.setBounds(340, 380, 290, 30);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre", "documento", "telefono", "barrio", "estrato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(0, 220, 590, 90);

        BotonEliminar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });
        jPanel6.add(BotonEliminar);
        BotonEliminar.setBounds(410, 420, 100, 30);
        jPanel6.add(jTextField2);
        jTextField2.setBounds(200, 420, 180, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 660, 540);

        jPanel2.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Registrarse");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(240, 40, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ususario");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(90, 130, 60, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Contraseña");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(90, 200, 70, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(270, 120, 220, 30);

        jButton5.setText("Registrarse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(390, 380, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Rol");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(100, 320, 50, 17);

        jButton6.setText("Atras");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(120, 380, 90, 30);
        jPanel2.add(jPasswordField2);
        jPasswordField2.setBounds(270, 190, 220, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Secretaria", "Estudiante" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(280, 310, 210, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Confirme contraseña");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 260, 160, 17);
        jPanel2.add(jPasswordField3);
        jPasswordField3.setBounds(270, 250, 220, 30);

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel10);
        jLabel10.setBounds(270, 230, 200, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 600, 500);

        jPanel4.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel4.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel4.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Actualizar");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(240, 30, 100, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nombre");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(40, 100, 70, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Documento");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(40, 170, 120, 17);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Telefono");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(40, 230, 60, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Barrio");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(40, 290, 70, 17);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Estrato");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(40, 340, 100, 20);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(170, 100, 180, 30);
        jPanel4.add(jTextField6);
        jTextField6.setBounds(170, 160, 180, 30);
        jPanel4.add(jTextField12);
        jTextField12.setBounds(170, 220, 180, 30);
        jPanel4.add(jTextField13);
        jTextField13.setBounds(170, 280, 180, 30);
        jPanel4.add(jTextField14);
        jTextField14.setBounds(170, 340, 180, 30);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(410, 410, 100, 30);
        jPanel4.add(jTextField15);
        jTextField15.setBounds(400, 190, 140, 30);

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(430, 250, 80, 30);

        jButton9.setText("Atras");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);
        jButton9.setBounds(90, 410, 90, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 680, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        // TODO add your handling code here:
        try {
            Conectadb sqlite = new Conectadb();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String cadSQL = null;

            cadSQL = "SELECT *FROM registro;";
            rs = stmt.executeQuery(cadSQL);
            String usuario = jTextField3.getText();
            String clave = jPasswordField1.getText();

            while (rs.next()) {
                if (usuario.equals(rs.getString(1)) && clave.equals(rs.getString(2))) {
                    if (rs.getString(4).equals("Estudiante")) {
                        jPanel1.setVisible(false);
                        jPanel3.setVisible(true);
                        jPanel6.setVisible(false);

                        System.out.println("Estudiante inicio sesión// Fecha: " + da.getTime().getDay() + "/" + (da.getTime().getMonth() + 1) + "/" + ((da.getTime().getYear()) + 1900) + " Hora: " + da.getTime().getHours() + ":" + da.getTime().getMinutes() + ":" + da.getTime().getSeconds());
                    }
                    if (rs.getString(4).equals("Administrador")) {
                        jPanel1.setVisible(false);
                        jPanel3.setVisible(false);
                        jPanel6.setVisible(true);
                        consulta = 1;
                        System.out.println("Administrador inicio sesión// Fecha: " + da.getTime().getDay() + "/" + (da.getTime().getMonth() + 1) + "/" + ((da.getTime().getYear()) + 1900) + " Hora: " + da.getTime().getHours() + ":" + da.getTime().getMinutes() + ":" + da.getTime().getSeconds());

                    }
                    if (rs.getString(4).equals("Secretaria")) {
                        jPanel1.setVisible(false);
                        jPanel3.setVisible(false);
                        jPanel6.setVisible(true);
                        consulta = 2;
                        System.out.println("Secretaria inicio sesión// Fecha: " + da.getTime().getDay() + "/" + (da.getTime().getMonth() + 1) + "/" + ((da.getTime().getYear()) + 1900) + " Hora: " + da.getTime().getHours() + ":" + da.getTime().getMinutes() + ":" + da.getTime().getSeconds());
                    }
                } else {
                    jLabel1.setText("Datos incorrectos");
                }
            }
            rs.close();
            stmt.close();
            cn.close();
            
            jTextField2.setText("");
            Buscar.setText("");

        } catch (SQLException ex) {

        }


    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void BotonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnviarActionPerformed
        // TODO add your handling code here:
        try {
            Conectadb sqlite = new Conectadb();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();

            String cadSQL = "INSERT INTO form_ben VALUES('" + jTextField7.getText() + "','" + jTextField8.getText() + "','" + jTextField9.getText() + "','" + jTextField10.getText() + "','" + jTextField11.getText() + "')";
            int r = stmt.executeUpdate(cadSQL);
            System.out.println(r + "Registro agregado.");

            stmt.close();

            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");

        } catch (SQLException ex) {

        }
        System.out.println("Estudiante envió formulario// Fecha: " + da.getTime().getDay() + "/" + (da.getTime().getMonth() + 1) + "/" + ((da.getTime().getYear()) + 1900) + "Hora: " + da.getTime().getHours() + ":" + da.getTime().getMinutes() + ":" + da.getTime().getSeconds());
    }//GEN-LAST:event_BotonEnviarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here;
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
        jPanel6.setVisible(false);
        jLabel1.setText("");
        jTextField3.setText("");
        jPasswordField1.setText("");
        System.out.println("Estudiante cerró sesión Fecha: " + da.getTime().getDay() + "/" + (da.getTime().getMonth() + 1) + "/" + ((da.getTime().getYear()) + 1900) + "Hora: " + da.getTime().getHours() + ":" + da.getTime().getMinutes() + ":" + da.getTime().getSeconds());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            if (jPasswordField2.getText().equals(jPasswordField3.getText())) {

                Conectadb sqlite = new Conectadb();
                Connection cn = sqlite.Conectar();
                Statement stmt = cn.createStatement();
                char[] ps = jPasswordField2.getPassword();
                String password = new String(ps);
                String cadSQL = "INSERT INTO registro VALUES('" + jTextField1.getText() + "','" + jPasswordField2.getText() + "','" + jPasswordField3.getText() + "','" + jComboBox1.getSelectedItem() + "')";
                int r = stmt.executeUpdate(cadSQL);
                System.out.println(r + "Registro agregado.");

                stmt.close();
                jLabel10.setText("");
                jTextField1.setText("");
                jPasswordField2.setText("");
                jPasswordField3.setText("");
            } else {
                System.out.println("la contraseña esta incorrecta");
                jLabel10.setText("La contraseña esta incorrecta");
                jPasswordField2.setText("");
                jPasswordField3.setText("");
            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel6.setVisible(false);
        jPanel4.setVisible(false);
        jLabel1.setText("");
        jTextField3.setText("");
        jPasswordField1.setText("");

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Conectadb sqlite = new Conectadb();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();

            if (jTextField5.getText().equals("") || jTextField6.getText().equals("") || jTextField12.getText().equals("") || jTextField13.getText().equals("") || jTextField14.getText().equals("")) {
                avisoactuali.setText("Los campos estan vacios No es posible Actualizar");
            } else {
                String busquedaSQL = "UPDATE form_ben SET nombre = '" + jTextField5.getText() + "', documento = '" + jTextField6.getText() + "', telefono = '" + jTextField12.getText() + "', barrio = '" + jTextField13.getText() + "', estrato = '" + jTextField14.getText() + "' WHERE NOMBRE = '" + jTextField5.getText() + "';";
                System.out.println(busquedaSQL);
                int r = stmt.executeUpdate(busquedaSQL);
                stmt.close();
                cn.close();
                System.out.println("Se Ingreso Exitosamente");
            }
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
            jTextField14.setText("");

        } catch (SQLException sq2) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el registro");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {
            Conectadb sqlite = new Conectadb();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String cadSQL = null;

            cadSQL = "SELECT *FROM form_ben WHERE nombre='" + jTextField15.getText() + "';";
            rs = stmt.executeQuery(cadSQL);

            jTextField5.setText(rs.getString(1));
            jTextField6.setText(rs.getString(2));
            jTextField12.setText(rs.getString(3));
            jTextField13.setText(rs.getString(4));
            jTextField14.setText(rs.getString(5));

            rs.close();
            stmt.close();
            cn.close();

        } catch (SQLException ex) {
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel6.setVisible(false);
        jPanel4.setVisible(false);
        jLabel1.setText("");
        jTextField3.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            Conectadb sqlite = new Conectadb();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String cadSQL = null;

            cadSQL = "SELECT *FROM form_ben WHERE nombre='" + Buscar.getText() + "';";
            rs = stmt.executeQuery(cadSQL);
            System.out.println(cadSQL);

            DefaultTableModel tabla = (DefaultTableModel) jTable3.getModel();
            Object[] filas = new Object[jTable3.getColumnCount()];

            while (rs.next()) {

                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);

                tabla.addRow(filas);
            }

            rs.close();
            stmt.close();
            cn.close();

        } catch (SQLException ex) {
            System.out.println("No esta Buscando");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel6.setVisible(false);
        jPanel4.setVisible(false);
        jLabel1.setText("");
        jTextField3.setText("");
        jPasswordField1.setText("");
        if (consulta == 1) {
            System.out.println("Administrador Cerró Sesión// Fecha: " + da.getTime().getDay() + "/" + (da.getTime().getMonth() + 1) + "/" + ((da.getTime().getYear()) + 1900) + "Hora: " + da.getTime().getHours() + ":" + da.getTime().getMinutes() + ":" + da.getTime().getSeconds());

        } else if (consulta == 2) {
            System.out.println("Secretaria Cerró Sesión// Fecha: " + da.getTime().getDay() + "/" + (da.getTime().getMonth() + 1) + "/" + ((da.getTime().getYear()) + 1900) + "Hora: " + da.getTime().getHours() + ":" + da.getTime().getMinutes() + ":" + da.getTime().getSeconds());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActualizarActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel6.setVisible(false);
        jPanel4.setVisible(true);

    }//GEN-LAST:event_jButton1ActualizarActionPerformed

    private void BotonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarActionPerformed
        // TODO add your handling code here:
        try {
            Conectadb sqlite = new Conectadb();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String cadSQL = null;

            cadSQL = "SELECT *FROM form_ben;";
            rs = stmt.executeQuery(cadSQL);

            DefaultTableModel tabla = (DefaultTableModel) jTable2.getModel();
            Object[] filas = new Object[jTable2.getColumnCount()];
            while (rs.next()) {
                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);

                tabla.addRow(filas);
            }
            rs.close();
            stmt.close();
            cn.close();
            if (consulta == 1) {
                System.out.println("Administrador consultó los registros// Fecha: " + da.getTime().getDay() + "/" + (da.getTime().getMonth() + 1) + "/" + ((da.getTime().getYear()) + 1900) + "Hora: " + da.getTime().getHours() + ":" + da.getTime().getMinutes() + ":" + da.getTime().getSeconds());

            } else if (consulta == 2) {
                System.out.println("Secretaria consultó los registros// Fecha: " + da.getTime().getDay() + "/" + (da.getTime().getMonth() + 1) + "/" + ((da.getTime().getYear()) + 1900) + "Hora: " + da.getTime().getHours() + ":" + da.getTime().getMinutes() + ":" + da.getTime().getSeconds());
            }

        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_BotonConsultarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed

        try {
            Conectadb sqlite = new Conectadb();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement(); //aqui estas abriendo el statement!!!!
            //ahi va sin parentesis
            String j = "delete from form_ben where nombre = '" + jTextField2.getText() + "';"; //intente nmos otra vezok
            System.out.println(j);
            int t = stmt.executeUpdate(j);
            stmt.close(); // ponlo a correr, pero recuerda que ya tiene uno abierto
            //vas a cerrar aqui // cierra aqui
            //vas a volver abrir aqui
            // don
            DefaultTableModel tableModel = (DefaultTableModel) jTable3.getModel();
            Object[] filas = new Object[jTable3.getColumnCount()];
        //eso lo vas a poner aqui
            for (int i = jTable3.getRowCount() - 1; i >= 0; i--) {
                    ((DefaultTableModel) jTable3.getModel()).removeRow(i);
                }
            //aqui tambien le falta punt y coma donde?
            ResultSet rs = stmt.executeQuery("select *from form_ben;");//ESTA ES MOSTRANDO LA LISTA
            //jmm HELP ya creo como solucionarlo

            while (rs.next()) {
                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);

                tableModel.addRow(filas);
            }
            //y aqui 
            rs.close();
            stmt.close();
            cn.close();
            //YAA ok espera
        } catch (SQLException y) {
            JOptionPane.showMessageDialog(null, y);
        }

    }//GEN-LAST:event_BotonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConsultar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonEnviar;
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JTextField Buscar;
    private javax.swing.JLabel avisoactuali;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Actualizar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
